/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Abdeljelil' at '20/01/17 7:27 PM' with Gradle 3.0
 *
 * @author Abdeljelil, @date 20/01/17 7:27 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
